### ISSUE TITLE
White code block on dark Cosmonaut theme.

### ISSUE THREAD

**Issue by lkhphuc** [azlen/roam-themes#1]
Hi, first thank a lot for your work. It is awesome and the Zenith theme works flawlessly.

But when trying out the Cosmonaut theme, I found that the Codeblock remain white in the background and some character cannot be seen.
<img width="662" alt="Screenshot 2020-06-05 at 01 14 11" src="https://user-images.githubusercontent.com/12573521/83822758-df1bcd80-a6c9-11ea-9f8e-a17182feab30.png">

Just want to let you know if you have time to fix in the future. For now I'm sticking with Zenith.

Again thank you very much.

**Comment by lkhphuc** [comment]
Well actually using the Zenith theme and then revert the color with Dark Reader extension look really great.
<img width="870" alt="Screenshot 2020-06-05 at 01 17 26" src="https://user-images.githubusercontent.com/12573521/83822908-53567100-a6ca-11ea-9677-0071557f047f.png">

**Comment by azlen** [comment]
Fixed! added code block styling to cosmonaut.css

![Screenshot from 2020-06-04 22-40-24](https://user-images.githubusercontent.com/934683/83840837-6bbb9100-a6b4-11ea-933b-929941fb2b0e.png)
