### ISSUE TITLE
Cosmonaut theme: white text on white background on contextual pop-up menu

### ISSUE THREAD

**Issue by keikhcheung** [azlen/roam-themes#2]
Contextual pop-up menu (the general `…` menu) shows white text on white background.

<img width="341" alt="Screenshot 2020-06-05 at 12 21 55" src="https://user-images.githubusercontent.com/22561336/83866079-8844e100-a727-11ea-91ea-6968953fa18e.png">

It is probably due to the default CSS defining `.bp3-menu` with `#fff` background.

<img width="915" alt="Screenshot 2020-06-05 at 12 24 02" src="https://user-images.githubusercontent.com/22561336/83866238-cf32d680-a727-11ea-9e93-4023a8d028be.png">

**Comment by azlen** [comment]
![Screenshot from 2020-06-05 13-44-29](https://user-images.githubusercontent.com/934683/83921195-b2e86700-a732-11ea-8492-3f8b15b82dd6.png)

Fixed in latest update
