### ISSUE TITLE
Cosmonaut Theme: too low in contrast to see references number.

### ISSUE THREAD

**Issue by fky2015** [azlen/roam-themes#6]
![image](https://user-images.githubusercontent.com/16451516/83902555-29b34d80-a78f-11ea-8663-9a224a017e0a.png)

**Comment by azlen** [comment]
![Screenshot from 2020-06-05 13-42-14](https://user-images.githubusercontent.com/934683/83921045-69981780-a732-11ea-9a83-311e65ec1d42.png)

Fixed in latest update
